# Generated by Django 3.2.9 on 2021-12-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospitalname', models.CharField(max_length=100)),
                ('vaccinename', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('patientname', models.CharField(max_length=100)),
                ('patientemail', models.CharField(max_length=100)),
                ('doctorname', models.CharField(max_length=100)),
                ('status', models.CharField(default='pending', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='docrequest',
            fields=[
                ('Id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, primary_key='True', serialize=False)),
                ('Aadharno', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('Status', models.CharField(default='Pending', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='doctorregistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospitalname', models.CharField(max_length=100)),
                ('doctorname', models.CharField(max_length=100)),
                ('doctoremail', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('status', models.CharField(default='pending', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='medicalreport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='')),
                ('Filedata', models.BinaryField()),
                ('Dataone', models.BinaryField()),
                ('Datatwo', models.BinaryField()),
                ('Hash1', models.CharField(max_length=100)),
                ('Hash2', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='patientdetails',
            fields=[
                ('slno', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, primary_key='True', serialize=False)),
                ('Aadharno', models.CharField(max_length=100, unique='True')),
                ('password', models.CharField(max_length=100)),
                ('contact', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=100)),
                ('Status', models.CharField(default='pending', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='reportsupload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tkid', models.IntegerField()),
                ('fever', models.CharField(max_length=100)),
                ('cough', models.CharField(max_length=100)),
                ('throat', models.CharField(max_length=100)),
                ('breath', models.CharField(max_length=100)),
                ('Covid', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('smoking', models.CharField(max_length=100)),
                ('alcohol', models.CharField(max_length=100)),
                ('saltdiet', models.CharField(max_length=100)),
                ('fatdiet', models.CharField(max_length=100)),
                ('exercise', models.CharField(max_length=100)),
                ('cholestrol', models.CharField(max_length=100)),
                ('bp', models.CharField(max_length=100)),
                ('sugar', models.CharField(max_length=100)),
                ('patientemail', models.CharField(max_length=100)),
            ],
        ),
    ]
